<?php
/**
 * WebshopApi
 * PHP version 5
 *
 * @category Class
 * @package  Vismutx\EasycreditApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ratenkauf REST API
 *
 * Version: V2  With the help of the REST API, webshop operators or business partners can integrate the ratenkauf by easyCredit into a webshop. Thus you have the possibility to integrate the ratenkauf by easyCredit into your webshop according to your own needs.  To initialize and complete a Ratenkauf using the REST API,the webshop system must authenticate itself against the REST API installment purchase. To do this, the webshop ID and the API password must be entered in the respective attributes in the header of the request.  You will receive your personal webshop identification after conclusion of the contract with us.  Would you like to use installment purchase by easyCredit?  Register directly under: [Registration](https://www.easycredit.de/ratenkaufpartner/registrierung.htm) and we will get in touch with you.   On our Ratenkauf Partner Site [Ratenkauf Partner Site](https://www.easycredit-ratenkauf.de/einbindung.htm)  we provide many shop plugins and additional integration guides.  API Root URL: https://ratenkauf.easycredit.de/ratenkauf-ws/rest/v2
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Vismutx\EasycreditApiPhp\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Vismutx\EasycreditApiPhp\ApiException;
use Vismutx\EasycreditApiPhp\Configuration;
use Vismutx\EasycreditApiPhp\HeaderSelector;
use Vismutx\EasycreditApiPhp\ObjectSerializer;

/**
 * WebshopApi Class Doc Comment
 *
 * @category Class
 * @package  Vismutx\EasycreditApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WebshopApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation abfrageRestbetragAnkaufobergrenze
     *
     * Loads the remaining amount of the purchase limit for the webshop
     *
     * @param  string $tbk_rk_shop Webshop-ID (required)
     * @param  string $tbk_rk_token API-Password (required)
     * @param  string $webshopkennung A valid Webshop-ID (required)
     *
     * @throws \Vismutx\EasycreditApiPhp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Vismutx\EasycreditApiPhp\Model\RestbetragAnkaufobergrenzeResponse
     */
    public function abfrageRestbetragAnkaufobergrenze($tbk_rk_shop, $tbk_rk_token, $webshopkennung)
    {
        list($response) = $this->abfrageRestbetragAnkaufobergrenzeWithHttpInfo($tbk_rk_shop, $tbk_rk_token, $webshopkennung);
        return $response;
    }

    /**
     * Operation abfrageRestbetragAnkaufobergrenzeWithHttpInfo
     *
     * Loads the remaining amount of the purchase limit for the webshop
     *
     * @param  string $tbk_rk_shop Webshop-ID (required)
     * @param  string $tbk_rk_token API-Password (required)
     * @param  string $webshopkennung A valid Webshop-ID (required)
     *
     * @throws \Vismutx\EasycreditApiPhp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Vismutx\EasycreditApiPhp\Model\RestbetragAnkaufobergrenzeResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function abfrageRestbetragAnkaufobergrenzeWithHttpInfo($tbk_rk_shop, $tbk_rk_token, $webshopkennung)
    {
        $returnType = '\Vismutx\EasycreditApiPhp\Model\RestbetragAnkaufobergrenzeResponse';
        $request = $this->abfrageRestbetragAnkaufobergrenzeRequest($tbk_rk_shop, $tbk_rk_token, $webshopkennung);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Vismutx\EasycreditApiPhp\Model\RestbetragAnkaufobergrenzeResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation abfrageRestbetragAnkaufobergrenzeAsync
     *
     * Loads the remaining amount of the purchase limit for the webshop
     *
     * @param  string $tbk_rk_shop Webshop-ID (required)
     * @param  string $tbk_rk_token API-Password (required)
     * @param  string $webshopkennung A valid Webshop-ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function abfrageRestbetragAnkaufobergrenzeAsync($tbk_rk_shop, $tbk_rk_token, $webshopkennung)
    {
        return $this->abfrageRestbetragAnkaufobergrenzeAsyncWithHttpInfo($tbk_rk_shop, $tbk_rk_token, $webshopkennung)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation abfrageRestbetragAnkaufobergrenzeAsyncWithHttpInfo
     *
     * Loads the remaining amount of the purchase limit for the webshop
     *
     * @param  string $tbk_rk_shop Webshop-ID (required)
     * @param  string $tbk_rk_token API-Password (required)
     * @param  string $webshopkennung A valid Webshop-ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function abfrageRestbetragAnkaufobergrenzeAsyncWithHttpInfo($tbk_rk_shop, $tbk_rk_token, $webshopkennung)
    {
        $returnType = '\Vismutx\EasycreditApiPhp\Model\RestbetragAnkaufobergrenzeResponse';
        $request = $this->abfrageRestbetragAnkaufobergrenzeRequest($tbk_rk_shop, $tbk_rk_token, $webshopkennung);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'abfrageRestbetragAnkaufobergrenze'
     *
     * @param  string $tbk_rk_shop Webshop-ID (required)
     * @param  string $tbk_rk_token API-Password (required)
     * @param  string $webshopkennung A valid Webshop-ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function abfrageRestbetragAnkaufobergrenzeRequest($tbk_rk_shop, $tbk_rk_token, $webshopkennung)
    {
        // verify the required parameter 'tbk_rk_shop' is set
        if ($tbk_rk_shop === null || (is_array($tbk_rk_shop) && count($tbk_rk_shop) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tbk_rk_shop when calling abfrageRestbetragAnkaufobergrenze'
            );
        }
        // verify the required parameter 'tbk_rk_token' is set
        if ($tbk_rk_token === null || (is_array($tbk_rk_token) && count($tbk_rk_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tbk_rk_token when calling abfrageRestbetragAnkaufobergrenze'
            );
        }
        // verify the required parameter 'webshopkennung' is set
        if ($webshopkennung === null || (is_array($webshopkennung) && count($webshopkennung) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $webshopkennung when calling abfrageRestbetragAnkaufobergrenze'
            );
        }

        $resourcePath = '/webshop/{webshopkennung}/restbetragankaufobergrenze';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($tbk_rk_shop !== null) {
            $headerParams['tbk-rk-shop'] = ObjectSerializer::toHeaderValue($tbk_rk_shop);
        }
        // header params
        if ($tbk_rk_token !== null) {
            $headerParams['tbk-rk-token'] = ObjectSerializer::toHeaderValue($tbk_rk_token);
        }

        // path params
        if ($webshopkennung !== null) {
            $resourcePath = str_replace(
                '{' . 'webshopkennung' . '}',
                ObjectSerializer::toPathValue($webshopkennung),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\Utils::jsonEncode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
