<?php
/**
 * Rechnungsadresse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vismutx\EasycreditApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ratenkauf REST API
 *
 * Version: V2  With the help of the REST API, webshop operators or business partners can integrate the ratenkauf by easyCredit into a webshop. Thus you have the possibility to integrate the ratenkauf by easyCredit into your webshop according to your own needs.  To initialize and complete a Ratenkauf using the REST API,the webshop system must authenticate itself against the REST API installment purchase. To do this, the webshop ID and the API password must be entered in the respective attributes in the header of the request.  You will receive your personal webshop identification after conclusion of the contract with us.  Would you like to use installment purchase by easyCredit?  Register directly under: [Registration](https://www.easycredit.de/ratenkaufpartner/registrierung.htm) and we will get in touch with you.   On our Ratenkauf Partner Site [Ratenkauf Partner Site](https://www.easycredit-ratenkauf.de/einbindung.htm)  we provide many shop plugins and additional integration guides.  API Root URL: https://ratenkauf.easycredit.de/ratenkauf-ws/rest/v2
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Vismutx\EasycreditApiPhp\Model;

use \ArrayAccess;
use \Vismutx\EasycreditApiPhp\ObjectSerializer;

/**
 * Rechnungsadresse Class Doc Comment
 *
 * @category Class
 * @description billing address
 * @package  Vismutx\EasycreditApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Rechnungsadresse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Rechnungsadresse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'strasse_haus_nr' => 'string',
        'adresszusatz' => 'string',
        'plz' => 'string',
        'ort' => 'string',
        'land' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'strasse_haus_nr' => null,
        'adresszusatz' => null,
        'plz' => null,
        'ort' => null,
        'land' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'strasse_haus_nr' => 'strasseHausNr',
        'adresszusatz' => 'adresszusatz',
        'plz' => 'plz',
        'ort' => 'ort',
        'land' => 'land'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'strasse_haus_nr' => 'setStrasseHausNr',
        'adresszusatz' => 'setAdresszusatz',
        'plz' => 'setPlz',
        'ort' => 'setOrt',
        'land' => 'setLand'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'strasse_haus_nr' => 'getStrasseHausNr',
        'adresszusatz' => 'getAdresszusatz',
        'plz' => 'getPlz',
        'ort' => 'getOrt',
        'land' => 'getLand'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const LAND_DE = 'DE';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLandAllowableValues()
    {
        return [
            self::LAND_DE,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['strasse_haus_nr'] = isset($data['strasse_haus_nr']) ? $data['strasse_haus_nr'] : null;
        $this->container['adresszusatz'] = isset($data['adresszusatz']) ? $data['adresszusatz'] : null;
        $this->container['plz'] = isset($data['plz']) ? $data['plz'] : null;
        $this->container['ort'] = isset($data['ort']) ? $data['ort'] : null;
        $this->container['land'] = isset($data['land']) ? $data['land'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['strasse_haus_nr'] === null) {
            $invalidProperties[] = "'strasse_haus_nr' can't be null";
        }
        if ($this->container['plz'] === null) {
            $invalidProperties[] = "'plz' can't be null";
        }
        if ($this->container['ort'] === null) {
            $invalidProperties[] = "'ort' can't be null";
        }
        if ($this->container['land'] === null) {
            $invalidProperties[] = "'land' can't be null";
        }
        $allowedValues = $this->getLandAllowableValues();
        if (!is_null($this->container['land']) && !in_array($this->container['land'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'land', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets strasse_haus_nr
     *
     * @return string
     */
    public function getStrasseHausNr()
    {
        return $this->container['strasse_haus_nr'];
    }

    /**
     * Sets strasse_haus_nr
     *
     * @param string $strasse_haus_nr Street and house number
     *
     * @return $this
     */
    public function setStrasseHausNr($strasse_haus_nr)
    {
        $this->container['strasse_haus_nr'] = $strasse_haus_nr;

        return $this;
    }

    /**
     * Gets adresszusatz
     *
     * @return string
     */
    public function getAdresszusatz()
    {
        return $this->container['adresszusatz'];
    }

    /**
     * Sets adresszusatz
     *
     * @param string $adresszusatz adresszusatz
     *
     * @return $this
     */
    public function setAdresszusatz($adresszusatz)
    {
        $this->container['adresszusatz'] = $adresszusatz;

        return $this;
    }

    /**
     * Gets plz
     *
     * @return string
     */
    public function getPlz()
    {
        return $this->container['plz'];
    }

    /**
     * Sets plz
     *
     * @param string $plz zip code
     *
     * @return $this
     */
    public function setPlz($plz)
    {
        $this->container['plz'] = $plz;

        return $this;
    }

    /**
     * Gets ort
     *
     * @return string
     */
    public function getOrt()
    {
        return $this->container['ort'];
    }

    /**
     * Sets ort
     *
     * @param string $ort city
     *
     * @return $this
     */
    public function setOrt($ort)
    {
        $this->container['ort'] = $ort;

        return $this;
    }

    /**
     * Gets land
     *
     * @return string
     */
    public function getLand()
    {
        return $this->container['land'];
    }

    /**
     * Sets land
     *
     * @param string $land country
     *
     * @return $this
     */
    public function setLand($land)
    {
        $allowedValues = $this->getLandAllowableValues();
        if (!in_array($land, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'land', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['land'] = $land;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


