<?php
/**
 * VorgangSpeichernInput
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vismutx\EasycreditApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ratenkauf REST API
 *
 * Version: V2  With the help of the REST API, webshop operators or business partners can integrate the ratenkauf by easyCredit into a webshop. Thus you have the possibility to integrate the ratenkauf by easyCredit into your webshop according to your own needs.  To initialize and complete a Ratenkauf using the REST API,the webshop system must authenticate itself against the REST API installment purchase. To do this, the webshop ID and the API password must be entered in the respective attributes in the header of the request.  You will receive your personal webshop identification after conclusion of the contract with us.  Would you like to use installment purchase by easyCredit?  Register directly under: [Registration](https://www.easycredit.de/ratenkaufpartner/registrierung.htm) and we will get in touch with you.   On our Ratenkauf Partner Site [Ratenkauf Partner Site](https://www.easycredit-ratenkauf.de/einbindung.htm)  we provide many shop plugins and additional integration guides.  API Root URL: https://ratenkauf.easycredit.de/ratenkauf-ws/rest/v2
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Vismutx\EasycreditApiPhp\Model;

use \ArrayAccess;
use \Vismutx\EasycreditApiPhp\ObjectSerializer;

/**
 * VorgangSpeichernInput Class Doc Comment
 *
 * @category Class
 * @package  Vismutx\EasycreditApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VorgangSpeichernInput implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'VorgangSpeichernInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'laufzeit' => 'int',
        'person' => '\Vismutx\EasycreditApiPhp\Model\Personendaten',
        'beschaeftigungsdaten' => '\Vismutx\EasycreditApiPhp\Model\Beschaeftigungsdaten',
        'rechnungsadresse' => '\Vismutx\EasycreditApiPhp\Model\Rechnungsadresse',
        'lieferadresse' => '\Vismutx\EasycreditApiPhp\Model\Lieferadresse',
        'bankdaten_input' => '\Vismutx\EasycreditApiPhp\Model\BankdatenInput',
        'zustimmungserklaerung' => '\Vismutx\EasycreditApiPhp\Model\Zustimmungserklaerung',
        'kontakt' => '\Vismutx\EasycreditApiPhp\Model\Kontakt'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'laufzeit' => 'int32',
        'person' => null,
        'beschaeftigungsdaten' => null,
        'rechnungsadresse' => null,
        'lieferadresse' => null,
        'bankdaten_input' => null,
        'zustimmungserklaerung' => null,
        'kontakt' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'laufzeit' => 'laufzeit',
        'person' => 'person',
        'beschaeftigungsdaten' => 'beschaeftigungsdaten',
        'rechnungsadresse' => 'rechnungsadresse',
        'lieferadresse' => 'lieferadresse',
        'bankdaten_input' => 'bankdatenInput',
        'zustimmungserklaerung' => 'zustimmungserklaerung',
        'kontakt' => 'kontakt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'laufzeit' => 'setLaufzeit',
        'person' => 'setPerson',
        'beschaeftigungsdaten' => 'setBeschaeftigungsdaten',
        'rechnungsadresse' => 'setRechnungsadresse',
        'lieferadresse' => 'setLieferadresse',
        'bankdaten_input' => 'setBankdatenInput',
        'zustimmungserklaerung' => 'setZustimmungserklaerung',
        'kontakt' => 'setKontakt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'laufzeit' => 'getLaufzeit',
        'person' => 'getPerson',
        'beschaeftigungsdaten' => 'getBeschaeftigungsdaten',
        'rechnungsadresse' => 'getRechnungsadresse',
        'lieferadresse' => 'getLieferadresse',
        'bankdaten_input' => 'getBankdatenInput',
        'zustimmungserklaerung' => 'getZustimmungserklaerung',
        'kontakt' => 'getKontakt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const LAUFZEIT_12 = 12;
    const LAUFZEIT_24 = 24;
    const LAUFZEIT_36 = 36;
    const LAUFZEIT_48 = 48;
    const LAUFZEIT_60 = 60;
    const LAUFZEIT_72 = 72;
    const LAUFZEIT_84 = 84;
    const LAUFZEIT_96 = 96;
    const LAUFZEIT_108 = 108;
    const LAUFZEIT_120 = 120;
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLaufzeitAllowableValues()
    {
        return [
            self::LAUFZEIT_12,
            self::LAUFZEIT_24,
            self::LAUFZEIT_36,
            self::LAUFZEIT_48,
            self::LAUFZEIT_60,
            self::LAUFZEIT_72,
            self::LAUFZEIT_84,
            self::LAUFZEIT_96,
            self::LAUFZEIT_108,
            self::LAUFZEIT_120,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['laufzeit'] = isset($data['laufzeit']) ? $data['laufzeit'] : null;
        $this->container['person'] = isset($data['person']) ? $data['person'] : null;
        $this->container['beschaeftigungsdaten'] = isset($data['beschaeftigungsdaten']) ? $data['beschaeftigungsdaten'] : null;
        $this->container['rechnungsadresse'] = isset($data['rechnungsadresse']) ? $data['rechnungsadresse'] : null;
        $this->container['lieferadresse'] = isset($data['lieferadresse']) ? $data['lieferadresse'] : null;
        $this->container['bankdaten_input'] = isset($data['bankdaten_input']) ? $data['bankdaten_input'] : null;
        $this->container['zustimmungserklaerung'] = isset($data['zustimmungserklaerung']) ? $data['zustimmungserklaerung'] : null;
        $this->container['kontakt'] = isset($data['kontakt']) ? $data['kontakt'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['laufzeit'] === null) {
            $invalidProperties[] = "'laufzeit' can't be null";
        }
        $allowedValues = $this->getLaufzeitAllowableValues();
        if (!is_null($this->container['laufzeit']) && !in_array($this->container['laufzeit'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'laufzeit', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['person'] === null) {
            $invalidProperties[] = "'person' can't be null";
        }
        if ($this->container['beschaeftigungsdaten'] === null) {
            $invalidProperties[] = "'beschaeftigungsdaten' can't be null";
        }
        if ($this->container['rechnungsadresse'] === null) {
            $invalidProperties[] = "'rechnungsadresse' can't be null";
        }
        if ($this->container['lieferadresse'] === null) {
            $invalidProperties[] = "'lieferadresse' can't be null";
        }
        if ($this->container['bankdaten_input'] === null) {
            $invalidProperties[] = "'bankdaten_input' can't be null";
        }
        if ($this->container['zustimmungserklaerung'] === null) {
            $invalidProperties[] = "'zustimmungserklaerung' can't be null";
        }
        if ($this->container['kontakt'] === null) {
            $invalidProperties[] = "'kontakt' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets laufzeit
     *
     * @return int
     */
    public function getLaufzeit()
    {
        return $this->container['laufzeit'];
    }

    /**
     * Sets laufzeit
     *
     * @param int $laufzeit term
     *
     * @return $this
     */
    public function setLaufzeit($laufzeit)
    {
        $allowedValues = $this->getLaufzeitAllowableValues();
        if (!in_array($laufzeit, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'laufzeit', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['laufzeit'] = $laufzeit;

        return $this;
    }

    /**
     * Gets person
     *
     * @return \Vismutx\EasycreditApiPhp\Model\Personendaten
     */
    public function getPerson()
    {
        return $this->container['person'];
    }

    /**
     * Sets person
     *
     * @param \Vismutx\EasycreditApiPhp\Model\Personendaten $person person
     *
     * @return $this
     */
    public function setPerson($person)
    {
        $this->container['person'] = $person;

        return $this;
    }

    /**
     * Gets beschaeftigungsdaten
     *
     * @return \Vismutx\EasycreditApiPhp\Model\Beschaeftigungsdaten
     */
    public function getBeschaeftigungsdaten()
    {
        return $this->container['beschaeftigungsdaten'];
    }

    /**
     * Sets beschaeftigungsdaten
     *
     * @param \Vismutx\EasycreditApiPhp\Model\Beschaeftigungsdaten $beschaeftigungsdaten beschaeftigungsdaten
     *
     * @return $this
     */
    public function setBeschaeftigungsdaten($beschaeftigungsdaten)
    {
        $this->container['beschaeftigungsdaten'] = $beschaeftigungsdaten;

        return $this;
    }

    /**
     * Gets rechnungsadresse
     *
     * @return \Vismutx\EasycreditApiPhp\Model\Rechnungsadresse
     */
    public function getRechnungsadresse()
    {
        return $this->container['rechnungsadresse'];
    }

    /**
     * Sets rechnungsadresse
     *
     * @param \Vismutx\EasycreditApiPhp\Model\Rechnungsadresse $rechnungsadresse rechnungsadresse
     *
     * @return $this
     */
    public function setRechnungsadresse($rechnungsadresse)
    {
        $this->container['rechnungsadresse'] = $rechnungsadresse;

        return $this;
    }

    /**
     * Gets lieferadresse
     *
     * @return \Vismutx\EasycreditApiPhp\Model\Lieferadresse
     */
    public function getLieferadresse()
    {
        return $this->container['lieferadresse'];
    }

    /**
     * Sets lieferadresse
     *
     * @param \Vismutx\EasycreditApiPhp\Model\Lieferadresse $lieferadresse lieferadresse
     *
     * @return $this
     */
    public function setLieferadresse($lieferadresse)
    {
        $this->container['lieferadresse'] = $lieferadresse;

        return $this;
    }

    /**
     * Gets bankdaten_input
     *
     * @return \Vismutx\EasycreditApiPhp\Model\BankdatenInput
     */
    public function getBankdatenInput()
    {
        return $this->container['bankdaten_input'];
    }

    /**
     * Sets bankdaten_input
     *
     * @param \Vismutx\EasycreditApiPhp\Model\BankdatenInput $bankdaten_input bankdaten_input
     *
     * @return $this
     */
    public function setBankdatenInput($bankdaten_input)
    {
        $this->container['bankdaten_input'] = $bankdaten_input;

        return $this;
    }

    /**
     * Gets zustimmungserklaerung
     *
     * @return \Vismutx\EasycreditApiPhp\Model\Zustimmungserklaerung
     */
    public function getZustimmungserklaerung()
    {
        return $this->container['zustimmungserklaerung'];
    }

    /**
     * Sets zustimmungserklaerung
     *
     * @param \Vismutx\EasycreditApiPhp\Model\Zustimmungserklaerung $zustimmungserklaerung zustimmungserklaerung
     *
     * @return $this
     */
    public function setZustimmungserklaerung($zustimmungserklaerung)
    {
        $this->container['zustimmungserklaerung'] = $zustimmungserklaerung;

        return $this;
    }

    /**
     * Gets kontakt
     *
     * @return \Vismutx\EasycreditApiPhp\Model\Kontakt
     */
    public function getKontakt()
    {
        return $this->container['kontakt'];
    }

    /**
     * Sets kontakt
     *
     * @param \Vismutx\EasycreditApiPhp\Model\Kontakt $kontakt kontakt
     *
     * @return $this
     */
    public function setKontakt($kontakt)
    {
        $this->container['kontakt'] = $kontakt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


