<?php
/**
 * VorgangInitialisierenRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vismutx\EasycreditApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ratenkauf REST API
 *
 * Version: V2  With the help of the REST API, webshop operators or business partners can integrate the ratenkauf by easyCredit into a webshop. Thus you have the possibility to integrate the ratenkauf by easyCredit into your webshop according to your own needs.  To initialize and complete a Ratenkauf using the REST API,the webshop system must authenticate itself against the REST API installment purchase. To do this, the webshop ID and the API password must be entered in the respective attributes in the header of the request.  You will receive your personal webshop identification after conclusion of the contract with us.  Would you like to use installment purchase by easyCredit?  Register directly under: [Registration](https://www.easycredit.de/ratenkaufpartner/registrierung.htm) and we will get in touch with you.   On our Ratenkauf Partner Site [Ratenkauf Partner Site](https://www.easycredit-ratenkauf.de/einbindung.htm)  we provide many shop plugins and additional integration guides.  API Root URL: https://ratenkauf.easycredit.de/ratenkauf-ws/rest/v2
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Vismutx\EasycreditApiPhp\Model;

use \ArrayAccess;
use \Vismutx\EasycreditApiPhp\ObjectSerializer;

/**
 * VorgangInitialisierenRequest Class Doc Comment
 *
 * @category Class
 * @package  Vismutx\EasycreditApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VorgangInitialisierenRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'VorgangInitialisierenRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'integrationsart' => 'string',
        'shop_kennung' => 'string',
        'bestellwert' => 'float',
        'laufzeit' => 'int',
        'personendaten' => '\Vismutx\EasycreditApiPhp\Model\Personendaten',
        'beschaeftigungsdaten' => '\Vismutx\EasycreditApiPhp\Model\Beschaeftigungsdaten',
        'rechnungsadresse' => '\Vismutx\EasycreditApiPhp\Model\Rechnungsadresse',
        'lieferadresse' => '\Vismutx\EasycreditApiPhp\Model\Lieferadresse',
        'kontakt' => '\Vismutx\EasycreditApiPhp\Model\Kontakt',
        'bankdaten_input' => '\Vismutx\EasycreditApiPhp\Model\BankdatenInput',
        'weitere_kaeuferangaben' => '\Vismutx\EasycreditApiPhp\Model\WeitereKaeuferangaben',
        'risikorelevante_angaben' => '\Vismutx\EasycreditApiPhp\Model\RisikorelevanteAngaben',
        'vorgangskennung_shop' => 'string',
        'ruecksprungadressen' => '\Vismutx\EasycreditApiPhp\Model\Ruecksprungadressen',
        'warenkorbinfos' => '\Vismutx\EasycreditApiPhp\Model\Warenkorbinfo[]',
        'technische_shopparameter' => '\Vismutx\EasycreditApiPhp\Model\TechnischeShopparameter'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'integrationsart' => null,
        'shop_kennung' => null,
        'bestellwert' => null,
        'laufzeit' => 'int32',
        'personendaten' => null,
        'beschaeftigungsdaten' => null,
        'rechnungsadresse' => null,
        'lieferadresse' => null,
        'kontakt' => null,
        'bankdaten_input' => null,
        'weitere_kaeuferangaben' => null,
        'risikorelevante_angaben' => null,
        'vorgangskennung_shop' => null,
        'ruecksprungadressen' => null,
        'warenkorbinfos' => null,
        'technische_shopparameter' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'integrationsart' => 'integrationsart',
        'shop_kennung' => 'shopKennung',
        'bestellwert' => 'bestellwert',
        'laufzeit' => 'laufzeit',
        'personendaten' => 'personendaten',
        'beschaeftigungsdaten' => 'beschaeftigungsdaten',
        'rechnungsadresse' => 'rechnungsadresse',
        'lieferadresse' => 'lieferadresse',
        'kontakt' => 'kontakt',
        'bankdaten_input' => 'bankdatenInput',
        'weitere_kaeuferangaben' => 'weitereKaeuferangaben',
        'risikorelevante_angaben' => 'risikorelevanteAngaben',
        'vorgangskennung_shop' => 'vorgangskennungShop',
        'ruecksprungadressen' => 'ruecksprungadressen',
        'warenkorbinfos' => 'warenkorbinfos',
        'technische_shopparameter' => 'technischeShopparameter'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'integrationsart' => 'setIntegrationsart',
        'shop_kennung' => 'setShopKennung',
        'bestellwert' => 'setBestellwert',
        'laufzeit' => 'setLaufzeit',
        'personendaten' => 'setPersonendaten',
        'beschaeftigungsdaten' => 'setBeschaeftigungsdaten',
        'rechnungsadresse' => 'setRechnungsadresse',
        'lieferadresse' => 'setLieferadresse',
        'kontakt' => 'setKontakt',
        'bankdaten_input' => 'setBankdatenInput',
        'weitere_kaeuferangaben' => 'setWeitereKaeuferangaben',
        'risikorelevante_angaben' => 'setRisikorelevanteAngaben',
        'vorgangskennung_shop' => 'setVorgangskennungShop',
        'ruecksprungadressen' => 'setRuecksprungadressen',
        'warenkorbinfos' => 'setWarenkorbinfos',
        'technische_shopparameter' => 'setTechnischeShopparameter'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'integrationsart' => 'getIntegrationsart',
        'shop_kennung' => 'getShopKennung',
        'bestellwert' => 'getBestellwert',
        'laufzeit' => 'getLaufzeit',
        'personendaten' => 'getPersonendaten',
        'beschaeftigungsdaten' => 'getBeschaeftigungsdaten',
        'rechnungsadresse' => 'getRechnungsadresse',
        'lieferadresse' => 'getLieferadresse',
        'kontakt' => 'getKontakt',
        'bankdaten_input' => 'getBankdatenInput',
        'weitere_kaeuferangaben' => 'getWeitereKaeuferangaben',
        'risikorelevante_angaben' => 'getRisikorelevanteAngaben',
        'vorgangskennung_shop' => 'getVorgangskennungShop',
        'ruecksprungadressen' => 'getRuecksprungadressen',
        'warenkorbinfos' => 'getWarenkorbinfos',
        'technische_shopparameter' => 'getTechnischeShopparameter'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const INTEGRATIONSART_PAYMENT_PAGE = 'PAYMENT_PAGE';
    const INTEGRATIONSART_SERVICE_INTEGRATION = 'SERVICE_INTEGRATION';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getIntegrationsartAllowableValues()
    {
        return [
            self::INTEGRATIONSART_PAYMENT_PAGE,
            self::INTEGRATIONSART_SERVICE_INTEGRATION,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['integrationsart'] = isset($data['integrationsart']) ? $data['integrationsart'] : null;
        $this->container['shop_kennung'] = isset($data['shop_kennung']) ? $data['shop_kennung'] : null;
        $this->container['bestellwert'] = isset($data['bestellwert']) ? $data['bestellwert'] : null;
        $this->container['laufzeit'] = isset($data['laufzeit']) ? $data['laufzeit'] : null;
        $this->container['personendaten'] = isset($data['personendaten']) ? $data['personendaten'] : null;
        $this->container['beschaeftigungsdaten'] = isset($data['beschaeftigungsdaten']) ? $data['beschaeftigungsdaten'] : null;
        $this->container['rechnungsadresse'] = isset($data['rechnungsadresse']) ? $data['rechnungsadresse'] : null;
        $this->container['lieferadresse'] = isset($data['lieferadresse']) ? $data['lieferadresse'] : null;
        $this->container['kontakt'] = isset($data['kontakt']) ? $data['kontakt'] : null;
        $this->container['bankdaten_input'] = isset($data['bankdaten_input']) ? $data['bankdaten_input'] : null;
        $this->container['weitere_kaeuferangaben'] = isset($data['weitere_kaeuferangaben']) ? $data['weitere_kaeuferangaben'] : null;
        $this->container['risikorelevante_angaben'] = isset($data['risikorelevante_angaben']) ? $data['risikorelevante_angaben'] : null;
        $this->container['vorgangskennung_shop'] = isset($data['vorgangskennung_shop']) ? $data['vorgangskennung_shop'] : null;
        $this->container['ruecksprungadressen'] = isset($data['ruecksprungadressen']) ? $data['ruecksprungadressen'] : null;
        $this->container['warenkorbinfos'] = isset($data['warenkorbinfos']) ? $data['warenkorbinfos'] : null;
        $this->container['technische_shopparameter'] = isset($data['technische_shopparameter']) ? $data['technische_shopparameter'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['integrationsart'] === null) {
            $invalidProperties[] = "'integrationsart' can't be null";
        }
        $allowedValues = $this->getIntegrationsartAllowableValues();
        if (!is_null($this->container['integrationsart']) && !in_array($this->container['integrationsart'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'integrationsart', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['shop_kennung'] === null) {
            $invalidProperties[] = "'shop_kennung' can't be null";
        }
        if ($this->container['bestellwert'] === null) {
            $invalidProperties[] = "'bestellwert' can't be null";
        }
        if ($this->container['personendaten'] === null) {
            $invalidProperties[] = "'personendaten' can't be null";
        }
        if ($this->container['beschaeftigungsdaten'] === null) {
            $invalidProperties[] = "'beschaeftigungsdaten' can't be null";
        }
        if ($this->container['rechnungsadresse'] === null) {
            $invalidProperties[] = "'rechnungsadresse' can't be null";
        }
        if ($this->container['lieferadresse'] === null) {
            $invalidProperties[] = "'lieferadresse' can't be null";
        }
        if ($this->container['kontakt'] === null) {
            $invalidProperties[] = "'kontakt' can't be null";
        }
        if ($this->container['risikorelevante_angaben'] === null) {
            $invalidProperties[] = "'risikorelevante_angaben' can't be null";
        }
        if ($this->container['warenkorbinfos'] === null) {
            $invalidProperties[] = "'warenkorbinfos' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets integrationsart
     *
     * @return string
     */
    public function getIntegrationsart()
    {
        return $this->container['integrationsart'];
    }

    /**
     * Sets integrationsart
     *
     * @param string $integrationsart type of integration
     *
     * @return $this
     */
    public function setIntegrationsart($integrationsart)
    {
        $allowedValues = $this->getIntegrationsartAllowableValues();
        if (!in_array($integrationsart, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'integrationsart', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['integrationsart'] = $integrationsart;

        return $this;
    }

    /**
     * Gets shop_kennung
     *
     * @return string
     */
    public function getShopKennung()
    {
        return $this->container['shop_kennung'];
    }

    /**
     * Sets shop_kennung
     *
     * @param string $shop_kennung Webshop-ID
     *
     * @return $this
     */
    public function setShopKennung($shop_kennung)
    {
        $this->container['shop_kennung'] = $shop_kennung;

        return $this;
    }

    /**
     * Gets bestellwert
     *
     * @return float
     */
    public function getBestellwert()
    {
        return $this->container['bestellwert'];
    }

    /**
     * Sets bestellwert
     *
     * @param float $bestellwert order value
     *
     * @return $this
     */
    public function setBestellwert($bestellwert)
    {
        $this->container['bestellwert'] = $bestellwert;

        return $this;
    }

    /**
     * Gets laufzeit
     *
     * @return int
     */
    public function getLaufzeit()
    {
        return $this->container['laufzeit'];
    }

    /**
     * Sets laufzeit
     *
     * @param int $laufzeit term
     *
     * @return $this
     */
    public function setLaufzeit($laufzeit)
    {
        $this->container['laufzeit'] = $laufzeit;

        return $this;
    }

    /**
     * Gets personendaten
     *
     * @return \Vismutx\EasycreditApiPhp\Model\Personendaten
     */
    public function getPersonendaten()
    {
        return $this->container['personendaten'];
    }

    /**
     * Sets personendaten
     *
     * @param \Vismutx\EasycreditApiPhp\Model\Personendaten $personendaten personendaten
     *
     * @return $this
     */
    public function setPersonendaten($personendaten)
    {
        $this->container['personendaten'] = $personendaten;

        return $this;
    }

    /**
     * Gets beschaeftigungsdaten
     *
     * @return \Vismutx\EasycreditApiPhp\Model\Beschaeftigungsdaten
     */
    public function getBeschaeftigungsdaten()
    {
        return $this->container['beschaeftigungsdaten'];
    }

    /**
     * Sets beschaeftigungsdaten
     *
     * @param \Vismutx\EasycreditApiPhp\Model\Beschaeftigungsdaten $beschaeftigungsdaten beschaeftigungsdaten
     *
     * @return $this
     */
    public function setBeschaeftigungsdaten($beschaeftigungsdaten)
    {
        $this->container['beschaeftigungsdaten'] = $beschaeftigungsdaten;

        return $this;
    }

    /**
     * Gets rechnungsadresse
     *
     * @return \Vismutx\EasycreditApiPhp\Model\Rechnungsadresse
     */
    public function getRechnungsadresse()
    {
        return $this->container['rechnungsadresse'];
    }

    /**
     * Sets rechnungsadresse
     *
     * @param \Vismutx\EasycreditApiPhp\Model\Rechnungsadresse $rechnungsadresse rechnungsadresse
     *
     * @return $this
     */
    public function setRechnungsadresse($rechnungsadresse)
    {
        $this->container['rechnungsadresse'] = $rechnungsadresse;

        return $this;
    }

    /**
     * Gets lieferadresse
     *
     * @return \Vismutx\EasycreditApiPhp\Model\Lieferadresse
     */
    public function getLieferadresse()
    {
        return $this->container['lieferadresse'];
    }

    /**
     * Sets lieferadresse
     *
     * @param \Vismutx\EasycreditApiPhp\Model\Lieferadresse $lieferadresse lieferadresse
     *
     * @return $this
     */
    public function setLieferadresse($lieferadresse)
    {
        $this->container['lieferadresse'] = $lieferadresse;

        return $this;
    }

    /**
     * Gets kontakt
     *
     * @return \Vismutx\EasycreditApiPhp\Model\Kontakt
     */
    public function getKontakt()
    {
        return $this->container['kontakt'];
    }

    /**
     * Sets kontakt
     *
     * @param \Vismutx\EasycreditApiPhp\Model\Kontakt $kontakt kontakt
     *
     * @return $this
     */
    public function setKontakt($kontakt)
    {
        $this->container['kontakt'] = $kontakt;

        return $this;
    }

    /**
     * Gets bankdaten_input
     *
     * @return \Vismutx\EasycreditApiPhp\Model\BankdatenInput
     */
    public function getBankdatenInput()
    {
        return $this->container['bankdaten_input'];
    }

    /**
     * Sets bankdaten_input
     *
     * @param \Vismutx\EasycreditApiPhp\Model\BankdatenInput $bankdaten_input bankdaten_input
     *
     * @return $this
     */
    public function setBankdatenInput($bankdaten_input)
    {
        $this->container['bankdaten_input'] = $bankdaten_input;

        return $this;
    }

    /**
     * Gets weitere_kaeuferangaben
     *
     * @return \Vismutx\EasycreditApiPhp\Model\WeitereKaeuferangaben
     */
    public function getWeitereKaeuferangaben()
    {
        return $this->container['weitere_kaeuferangaben'];
    }

    /**
     * Sets weitere_kaeuferangaben
     *
     * @param \Vismutx\EasycreditApiPhp\Model\WeitereKaeuferangaben $weitere_kaeuferangaben weitere_kaeuferangaben
     *
     * @return $this
     */
    public function setWeitereKaeuferangaben($weitere_kaeuferangaben)
    {
        $this->container['weitere_kaeuferangaben'] = $weitere_kaeuferangaben;

        return $this;
    }

    /**
     * Gets risikorelevante_angaben
     *
     * @return \Vismutx\EasycreditApiPhp\Model\RisikorelevanteAngaben
     */
    public function getRisikorelevanteAngaben()
    {
        return $this->container['risikorelevante_angaben'];
    }

    /**
     * Sets risikorelevante_angaben
     *
     * @param \Vismutx\EasycreditApiPhp\Model\RisikorelevanteAngaben $risikorelevante_angaben risikorelevante_angaben
     *
     * @return $this
     */
    public function setRisikorelevanteAngaben($risikorelevante_angaben)
    {
        $this->container['risikorelevante_angaben'] = $risikorelevante_angaben;

        return $this;
    }

    /**
     * Gets vorgangskennung_shop
     *
     * @return string
     */
    public function getVorgangskennungShop()
    {
        return $this->container['vorgangskennung_shop'];
    }

    /**
     * Sets vorgangskennung_shop
     *
     * @param string $vorgangskennung_shop vorgangskennung_shop
     *
     * @return $this
     */
    public function setVorgangskennungShop($vorgangskennung_shop)
    {
        $this->container['vorgangskennung_shop'] = $vorgangskennung_shop;

        return $this;
    }

    /**
     * Gets ruecksprungadressen
     *
     * @return \Vismutx\EasycreditApiPhp\Model\Ruecksprungadressen
     */
    public function getRuecksprungadressen()
    {
        return $this->container['ruecksprungadressen'];
    }

    /**
     * Sets ruecksprungadressen
     *
     * @param \Vismutx\EasycreditApiPhp\Model\Ruecksprungadressen $ruecksprungadressen ruecksprungadressen
     *
     * @return $this
     */
    public function setRuecksprungadressen($ruecksprungadressen)
    {
        $this->container['ruecksprungadressen'] = $ruecksprungadressen;

        return $this;
    }

    /**
     * Gets warenkorbinfos
     *
     * @return \Vismutx\EasycreditApiPhp\Model\Warenkorbinfo[]
     */
    public function getWarenkorbinfos()
    {
        return $this->container['warenkorbinfos'];
    }

    /**
     * Sets warenkorbinfos
     *
     * @param \Vismutx\EasycreditApiPhp\Model\Warenkorbinfo[] $warenkorbinfos warenkorbinfos
     *
     * @return $this
     */
    public function setWarenkorbinfos($warenkorbinfos)
    {
        $this->container['warenkorbinfos'] = $warenkorbinfos;

        return $this;
    }

    /**
     * Gets technische_shopparameter
     *
     * @return \Vismutx\EasycreditApiPhp\Model\TechnischeShopparameter
     */
    public function getTechnischeShopparameter()
    {
        return $this->container['technische_shopparameter'];
    }

    /**
     * Sets technische_shopparameter
     *
     * @param \Vismutx\EasycreditApiPhp\Model\TechnischeShopparameter $technische_shopparameter technische_shopparameter
     *
     * @return $this
     */
    public function setTechnischeShopparameter($technische_shopparameter)
    {
        $this->container['technische_shopparameter'] = $technische_shopparameter;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


