<?php
/**
 * WeitereKaeuferangaben
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vismutx\EasycreditApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ratenkauf REST API
 *
 * Version: V2  With the help of the REST API, webshop operators or business partners can integrate the ratenkauf by easyCredit into a webshop. Thus you have the possibility to integrate the ratenkauf by easyCredit into your webshop according to your own needs.  To initialize and complete a Ratenkauf using the REST API,the webshop system must authenticate itself against the REST API installment purchase. To do this, the webshop ID and the API password must be entered in the respective attributes in the header of the request.  You will receive your personal webshop identification after conclusion of the contract with us.  Would you like to use installment purchase by easyCredit?  Register directly under: [Registration](https://www.easycredit.de/ratenkaufpartner/registrierung.htm) and we will get in touch with you.   On our Ratenkauf Partner Site [Ratenkauf Partner Site](https://www.easycredit-ratenkauf.de/einbindung.htm)  we provide many shop plugins and additional integration guides.  API Root URL: https://ratenkauf.easycredit.de/ratenkauf-ws/rest/v2
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Vismutx\EasycreditApiPhp\Model;

use \ArrayAccess;
use \Vismutx\EasycreditApiPhp\ObjectSerializer;

/**
 * WeitereKaeuferangaben Class Doc Comment
 *
 * @category Class
 * @description additional customer information
 * @package  Vismutx\EasycreditApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WeitereKaeuferangaben implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'WeitereKaeuferangaben';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'telefonnummer' => 'string',
        'titel' => 'string',
        'geburtsname' => 'string',
        'geburtsort' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'telefonnummer' => null,
        'titel' => null,
        'geburtsname' => null,
        'geburtsort' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'telefonnummer' => 'telefonnummer',
        'titel' => 'titel',
        'geburtsname' => 'geburtsname',
        'geburtsort' => 'geburtsort'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'telefonnummer' => 'setTelefonnummer',
        'titel' => 'setTitel',
        'geburtsname' => 'setGeburtsname',
        'geburtsort' => 'setGeburtsort'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'telefonnummer' => 'getTelefonnummer',
        'titel' => 'getTitel',
        'geburtsname' => 'getGeburtsname',
        'geburtsort' => 'getGeburtsort'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const TITEL_PROFDR = 'PROFDR';
    const TITEL_DR = 'DR';
    const TITEL_DRDR = 'DRDR';
    const TITEL_PROF = 'PROF';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTitelAllowableValues()
    {
        return [
            self::TITEL_PROFDR,
            self::TITEL_DR,
            self::TITEL_DRDR,
            self::TITEL_PROF,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['telefonnummer'] = isset($data['telefonnummer']) ? $data['telefonnummer'] : null;
        $this->container['titel'] = isset($data['titel']) ? $data['titel'] : null;
        $this->container['geburtsname'] = isset($data['geburtsname']) ? $data['geburtsname'] : null;
        $this->container['geburtsort'] = isset($data['geburtsort']) ? $data['geburtsort'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getTitelAllowableValues();
        if (!is_null($this->container['titel']) && !in_array($this->container['titel'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'titel', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets telefonnummer
     *
     * @return string
     */
    public function getTelefonnummer()
    {
        return $this->container['telefonnummer'];
    }

    /**
     * Sets telefonnummer
     *
     * @param string $telefonnummer phone number. format: 0 - 9 and -
     *
     * @return $this
     */
    public function setTelefonnummer($telefonnummer)
    {
        $this->container['telefonnummer'] = $telefonnummer;

        return $this;
    }

    /**
     * Gets titel
     *
     * @return string
     */
    public function getTitel()
    {
        return $this->container['titel'];
    }

    /**
     * Sets titel
     *
     * @param string $titel title
     *
     * @return $this
     */
    public function setTitel($titel)
    {
        $allowedValues = $this->getTitelAllowableValues();
        if (!is_null($titel) && !in_array($titel, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'titel', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['titel'] = $titel;

        return $this;
    }

    /**
     * Gets geburtsname
     *
     * @return string
     */
    public function getGeburtsname()
    {
        return $this->container['geburtsname'];
    }

    /**
     * Sets geburtsname
     *
     * @param string $geburtsname birth name
     *
     * @return $this
     */
    public function setGeburtsname($geburtsname)
    {
        $this->container['geburtsname'] = $geburtsname;

        return $this;
    }

    /**
     * Gets geburtsort
     *
     * @return string
     */
    public function getGeburtsort()
    {
        return $this->container['geburtsort'];
    }

    /**
     * Sets geburtsort
     *
     * @param string $geburtsort city of birth
     *
     * @return $this
     */
    public function setGeburtsort($geburtsort)
    {
        $this->container['geburtsort'] = $geburtsort;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


