<?php
/**
 * ZustimmungResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vismutx\EasycreditApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ratenkauf REST API
 *
 * Version: V2  With the help of the REST API, webshop operators or business partners can integrate the ratenkauf by easyCredit into a webshop. Thus you have the possibility to integrate the ratenkauf by easyCredit into your webshop according to your own needs.  To initialize and complete a Ratenkauf using the REST API,the webshop system must authenticate itself against the REST API installment purchase. To do this, the webshop ID and the API password must be entered in the respective attributes in the header of the request.  You will receive your personal webshop identification after conclusion of the contract with us.  Would you like to use installment purchase by easyCredit?  Register directly under: [Registration](https://www.easycredit.de/ratenkaufpartner/registrierung.htm) and we will get in touch with you.   On our Ratenkauf Partner Site [Ratenkauf Partner Site](https://www.easycredit-ratenkauf.de/einbindung.htm)  we provide many shop plugins and additional integration guides.  API Root URL: https://ratenkauf.easycredit.de/ratenkauf-ws/rest/v2
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Vismutx\EasycreditApiPhp\Model;

use \ArrayAccess;
use \Vismutx\EasycreditApiPhp\ObjectSerializer;

/**
 * ZustimmungResponse Class Doc Comment
 *
 * @category Class
 * @package  Vismutx\EasycreditApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ZustimmungResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ZustimmungResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ws_messages' => '\Vismutx\EasycreditApiPhp\Model\WsMessages',
        'uuid' => 'string',
        'tb_vorgangskennung' => 'string',
        'webshopkennung' => 'string',
        'timestamp' => 'int',
        'zustimmung_datenuebertragung_payment_page' => 'string',
        'zustimmung_datenuebertragung_service_integration' => 'string',
        'einwilligungs_erklaerung_service_integration' => 'string',
        'einwilligungs_erklaerung_pos' => 'string',
        'zustimmung_zur_handlung_in_eigenem_namen' => 'string',
        'zustimmung_email_werbung' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'ws_messages' => null,
        'uuid' => null,
        'tb_vorgangskennung' => null,
        'webshopkennung' => null,
        'timestamp' => 'int64',
        'zustimmung_datenuebertragung_payment_page' => null,
        'zustimmung_datenuebertragung_service_integration' => null,
        'einwilligungs_erklaerung_service_integration' => null,
        'einwilligungs_erklaerung_pos' => null,
        'zustimmung_zur_handlung_in_eigenem_namen' => null,
        'zustimmung_email_werbung' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ws_messages' => 'wsMessages',
        'uuid' => 'uuid',
        'tb_vorgangskennung' => 'tbVorgangskennung',
        'webshopkennung' => 'webshopkennung',
        'timestamp' => 'timestamp',
        'zustimmung_datenuebertragung_payment_page' => 'zustimmungDatenuebertragungPaymentPage',
        'zustimmung_datenuebertragung_service_integration' => 'zustimmungDatenuebertragungServiceIntegration',
        'einwilligungs_erklaerung_service_integration' => 'einwilligungsErklaerungServiceIntegration',
        'einwilligungs_erklaerung_pos' => 'einwilligungsErklaerungPos',
        'zustimmung_zur_handlung_in_eigenem_namen' => 'zustimmungZurHandlungInEigenemNamen',
        'zustimmung_email_werbung' => 'zustimmungEmailWerbung'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ws_messages' => 'setWsMessages',
        'uuid' => 'setUuid',
        'tb_vorgangskennung' => 'setTbVorgangskennung',
        'webshopkennung' => 'setWebshopkennung',
        'timestamp' => 'setTimestamp',
        'zustimmung_datenuebertragung_payment_page' => 'setZustimmungDatenuebertragungPaymentPage',
        'zustimmung_datenuebertragung_service_integration' => 'setZustimmungDatenuebertragungServiceIntegration',
        'einwilligungs_erklaerung_service_integration' => 'setEinwilligungsErklaerungServiceIntegration',
        'einwilligungs_erklaerung_pos' => 'setEinwilligungsErklaerungPos',
        'zustimmung_zur_handlung_in_eigenem_namen' => 'setZustimmungZurHandlungInEigenemNamen',
        'zustimmung_email_werbung' => 'setZustimmungEmailWerbung'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ws_messages' => 'getWsMessages',
        'uuid' => 'getUuid',
        'tb_vorgangskennung' => 'getTbVorgangskennung',
        'webshopkennung' => 'getWebshopkennung',
        'timestamp' => 'getTimestamp',
        'zustimmung_datenuebertragung_payment_page' => 'getZustimmungDatenuebertragungPaymentPage',
        'zustimmung_datenuebertragung_service_integration' => 'getZustimmungDatenuebertragungServiceIntegration',
        'einwilligungs_erklaerung_service_integration' => 'getEinwilligungsErklaerungServiceIntegration',
        'einwilligungs_erklaerung_pos' => 'getEinwilligungsErklaerungPos',
        'zustimmung_zur_handlung_in_eigenem_namen' => 'getZustimmungZurHandlungInEigenemNamen',
        'zustimmung_email_werbung' => 'getZustimmungEmailWerbung'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ws_messages'] = isset($data['ws_messages']) ? $data['ws_messages'] : null;
        $this->container['uuid'] = isset($data['uuid']) ? $data['uuid'] : null;
        $this->container['tb_vorgangskennung'] = isset($data['tb_vorgangskennung']) ? $data['tb_vorgangskennung'] : null;
        $this->container['webshopkennung'] = isset($data['webshopkennung']) ? $data['webshopkennung'] : null;
        $this->container['timestamp'] = isset($data['timestamp']) ? $data['timestamp'] : null;
        $this->container['zustimmung_datenuebertragung_payment_page'] = isset($data['zustimmung_datenuebertragung_payment_page']) ? $data['zustimmung_datenuebertragung_payment_page'] : null;
        $this->container['zustimmung_datenuebertragung_service_integration'] = isset($data['zustimmung_datenuebertragung_service_integration']) ? $data['zustimmung_datenuebertragung_service_integration'] : null;
        $this->container['einwilligungs_erklaerung_service_integration'] = isset($data['einwilligungs_erklaerung_service_integration']) ? $data['einwilligungs_erklaerung_service_integration'] : null;
        $this->container['einwilligungs_erklaerung_pos'] = isset($data['einwilligungs_erklaerung_pos']) ? $data['einwilligungs_erklaerung_pos'] : null;
        $this->container['zustimmung_zur_handlung_in_eigenem_namen'] = isset($data['zustimmung_zur_handlung_in_eigenem_namen']) ? $data['zustimmung_zur_handlung_in_eigenem_namen'] : null;
        $this->container['zustimmung_email_werbung'] = isset($data['zustimmung_email_werbung']) ? $data['zustimmung_email_werbung'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['ws_messages'] === null) {
            $invalidProperties[] = "'ws_messages' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ws_messages
     *
     * @return \Vismutx\EasycreditApiPhp\Model\WsMessages
     */
    public function getWsMessages()
    {
        return $this->container['ws_messages'];
    }

    /**
     * Sets ws_messages
     *
     * @param \Vismutx\EasycreditApiPhp\Model\WsMessages $ws_messages ws_messages
     *
     * @return $this
     */
    public function setWsMessages($ws_messages)
    {
        $this->container['ws_messages'] = $ws_messages;

        return $this;
    }

    /**
     * Gets uuid
     *
     * @return string
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param string $uuid uuid
     *
     * @return $this
     */
    public function setUuid($uuid)
    {
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets tb_vorgangskennung
     *
     * @return string
     */
    public function getTbVorgangskennung()
    {
        return $this->container['tb_vorgangskennung'];
    }

    /**
     * Sets tb_vorgangskennung
     *
     * @param string $tb_vorgangskennung tb_vorgangskennung
     *
     * @return $this
     */
    public function setTbVorgangskennung($tb_vorgangskennung)
    {
        $this->container['tb_vorgangskennung'] = $tb_vorgangskennung;

        return $this;
    }

    /**
     * Gets webshopkennung
     *
     * @return string
     */
    public function getWebshopkennung()
    {
        return $this->container['webshopkennung'];
    }

    /**
     * Sets webshopkennung
     *
     * @param string $webshopkennung webshopkennung
     *
     * @return $this
     */
    public function setWebshopkennung($webshopkennung)
    {
        $this->container['webshopkennung'] = $webshopkennung;

        return $this;
    }

    /**
     * Gets timestamp
     *
     * @return int
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param int $timestamp timestamp
     *
     * @return $this
     */
    public function setTimestamp($timestamp)
    {
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets zustimmung_datenuebertragung_payment_page
     *
     * @return string
     */
    public function getZustimmungDatenuebertragungPaymentPage()
    {
        return $this->container['zustimmung_datenuebertragung_payment_page'];
    }

    /**
     * Sets zustimmung_datenuebertragung_payment_page
     *
     * @param string $zustimmung_datenuebertragung_payment_page zustimmung_datenuebertragung_payment_page
     *
     * @return $this
     */
    public function setZustimmungDatenuebertragungPaymentPage($zustimmung_datenuebertragung_payment_page)
    {
        $this->container['zustimmung_datenuebertragung_payment_page'] = $zustimmung_datenuebertragung_payment_page;

        return $this;
    }

    /**
     * Gets zustimmung_datenuebertragung_service_integration
     *
     * @return string
     */
    public function getZustimmungDatenuebertragungServiceIntegration()
    {
        return $this->container['zustimmung_datenuebertragung_service_integration'];
    }

    /**
     * Sets zustimmung_datenuebertragung_service_integration
     *
     * @param string $zustimmung_datenuebertragung_service_integration zustimmung_datenuebertragung_service_integration
     *
     * @return $this
     */
    public function setZustimmungDatenuebertragungServiceIntegration($zustimmung_datenuebertragung_service_integration)
    {
        $this->container['zustimmung_datenuebertragung_service_integration'] = $zustimmung_datenuebertragung_service_integration;

        return $this;
    }

    /**
     * Gets einwilligungs_erklaerung_service_integration
     *
     * @return string
     */
    public function getEinwilligungsErklaerungServiceIntegration()
    {
        return $this->container['einwilligungs_erklaerung_service_integration'];
    }

    /**
     * Sets einwilligungs_erklaerung_service_integration
     *
     * @param string $einwilligungs_erklaerung_service_integration einwilligungs_erklaerung_service_integration
     *
     * @return $this
     */
    public function setEinwilligungsErklaerungServiceIntegration($einwilligungs_erklaerung_service_integration)
    {
        $this->container['einwilligungs_erklaerung_service_integration'] = $einwilligungs_erklaerung_service_integration;

        return $this;
    }

    /**
     * Gets einwilligungs_erklaerung_pos
     *
     * @return string
     */
    public function getEinwilligungsErklaerungPos()
    {
        return $this->container['einwilligungs_erklaerung_pos'];
    }

    /**
     * Sets einwilligungs_erklaerung_pos
     *
     * @param string $einwilligungs_erklaerung_pos einwilligungs_erklaerung_pos
     *
     * @return $this
     */
    public function setEinwilligungsErklaerungPos($einwilligungs_erklaerung_pos)
    {
        $this->container['einwilligungs_erklaerung_pos'] = $einwilligungs_erklaerung_pos;

        return $this;
    }

    /**
     * Gets zustimmung_zur_handlung_in_eigenem_namen
     *
     * @return string
     */
    public function getZustimmungZurHandlungInEigenemNamen()
    {
        return $this->container['zustimmung_zur_handlung_in_eigenem_namen'];
    }

    /**
     * Sets zustimmung_zur_handlung_in_eigenem_namen
     *
     * @param string $zustimmung_zur_handlung_in_eigenem_namen zustimmung_zur_handlung_in_eigenem_namen
     *
     * @return $this
     */
    public function setZustimmungZurHandlungInEigenemNamen($zustimmung_zur_handlung_in_eigenem_namen)
    {
        $this->container['zustimmung_zur_handlung_in_eigenem_namen'] = $zustimmung_zur_handlung_in_eigenem_namen;

        return $this;
    }

    /**
     * Gets zustimmung_email_werbung
     *
     * @return string
     */
    public function getZustimmungEmailWerbung()
    {
        return $this->container['zustimmung_email_werbung'];
    }

    /**
     * Sets zustimmung_email_werbung
     *
     * @param string $zustimmung_email_werbung zustimmung_email_werbung
     *
     * @return $this
     */
    public function setZustimmungEmailWerbung($zustimmung_email_werbung)
    {
        $this->container['zustimmung_email_werbung'] = $zustimmung_email_werbung;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


