<?php
/**
 * VorgangInitialisierenRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vismutx\EasycreditApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ratenkauf REST API
 *
 * Version: V2  With the help of the REST API, webshop operators or business partners can integrate the ratenkauf by easyCredit into a webshop. Thus you have the possibility to integrate the ratenkauf by easyCredit into your webshop according to your own needs.  To initialize and complete a Ratenkauf using the REST API,the webshop system must authenticate itself against the REST API installment purchase. To do this, the webshop ID and the API password must be entered in the respective attributes in the header of the request.  You will receive your personal webshop identification after conclusion of the contract with us.  Would you like to use installment purchase by easyCredit?  Register directly under: [Registration](https://www.easycredit.de/ratenkaufpartner/registrierung.htm) and we will get in touch with you.   On our Ratenkauf Partner Site [Ratenkauf Partner Site](https://www.easycredit-ratenkauf.de/einbindung.htm)  we provide many shop plugins and additional integration guides.  API Root URL: https://ratenkauf.easycredit.de/ratenkauf-ws/rest/v2
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vismutx\EasycreditApiPhp;

/**
 * VorgangInitialisierenRequestTest Class Doc Comment
 *
 * @category    Class
 * @description VorgangInitialisierenRequest
 * @package     Vismutx\EasycreditApiPhp
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VorgangInitialisierenRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VorgangInitialisierenRequest"
     */
    public function testVorgangInitialisierenRequest()
    {
    }

    /**
     * Test attribute "integrationsart"
     */
    public function testPropertyIntegrationsart()
    {
    }

    /**
     * Test attribute "shop_kennung"
     */
    public function testPropertyShopKennung()
    {
    }

    /**
     * Test attribute "bestellwert"
     */
    public function testPropertyBestellwert()
    {
    }

    /**
     * Test attribute "laufzeit"
     */
    public function testPropertyLaufzeit()
    {
    }

    /**
     * Test attribute "personendaten"
     */
    public function testPropertyPersonendaten()
    {
    }

    /**
     * Test attribute "beschaeftigungsdaten"
     */
    public function testPropertyBeschaeftigungsdaten()
    {
    }

    /**
     * Test attribute "rechnungsadresse"
     */
    public function testPropertyRechnungsadresse()
    {
    }

    /**
     * Test attribute "lieferadresse"
     */
    public function testPropertyLieferadresse()
    {
    }

    /**
     * Test attribute "kontakt"
     */
    public function testPropertyKontakt()
    {
    }

    /**
     * Test attribute "bankdaten_input"
     */
    public function testPropertyBankdatenInput()
    {
    }

    /**
     * Test attribute "weitere_kaeuferangaben"
     */
    public function testPropertyWeitereKaeuferangaben()
    {
    }

    /**
     * Test attribute "risikorelevante_angaben"
     */
    public function testPropertyRisikorelevanteAngaben()
    {
    }

    /**
     * Test attribute "vorgangskennung_shop"
     */
    public function testPropertyVorgangskennungShop()
    {
    }

    /**
     * Test attribute "ruecksprungadressen"
     */
    public function testPropertyRuecksprungadressen()
    {
    }

    /**
     * Test attribute "warenkorbinfos"
     */
    public function testPropertyWarenkorbinfos()
    {
    }

    /**
     * Test attribute "technische_shopparameter"
     */
    public function testPropertyTechnischeShopparameter()
    {
    }
}
